version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    container_name: kuke-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kukedb
      MYSQL_USER: kuke
      MYSQL_PASSWORD: kuke
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.4.3-alpine
    container_name: kuke-board-redis
    ports:
      - "6380:6379"
  kafka:
    image: apache/kafka:3.8.0
    container_name: kuke-board-kafka
    ports:
      - "9092:9092"

volumes:
  mysql_data: