server:
  port: 9000
#  port: 9100
spring:
  application:
    name: kuke-board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 127.0.0.1
      port: 6380
    kafka:
      bootstrap-servers: 127.0.0.1:9092
